# Generated by Django 3.1.7 on 2021-04-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstokenfb',
            old_name='profile',
            new_name='user',
        ),
    ]
