# Generated by Django 3.1.7 on 2021-05-27 16:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210422_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('titlepage1', models.CharField(max_length=150)),
                ('titlePageAccueil', models.CharField(max_length=150)),
                ('titlePageHowitworks', models.CharField(max_length=150)),
                ('titlePageService', models.CharField(max_length=150)),
                ('titlePageContact', models.CharField(max_length=150)),
                ('descriptionPage1', models.CharField(max_length=255)),
                ('descriptionPageAccueil', models.CharField(max_length=255)),
                ('descriptionPageHowitworks', models.CharField(max_length=255)),
                ('descriptionAboutus', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('descriptionPageContact', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('descriptionFacbook', models.CharField(max_length=255)),
                ('descriptionTwitter', models.CharField(max_length=255)),
                ('descriptionYoutube', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phone1', models.CharField(blank=True, max_length=15)),
                ('phone2', models.CharField(blank=True, max_length=50)),
                ('fax', models.CharField(blank=True, max_length=15)),
                ('email1', models.CharField(blank=True, max_length=50)),
                ('email2', models.CharField(blank=True, max_length=50)),
                ('facbook', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('youtube', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.CharField(blank=True, max_length=50)),
                ('reference', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='ip',
        ),
    ]
